[package]
name = "encryption-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
deluxe = "0.5.0"
proc-macro2 = "1.0.67"
quote = "1.0.9"
regex = "1.10.4"
syn = "2.0.37"

[lib]
proc-macro = true